### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by siddhantk232** [Taiwrash/dev-resume#24]
1. The logo in the Hero section should be a little big and the text should be center aligned.
2. The footer looks bad.
3. use read more link in the card description and maybe open a modal on click or enforce a ceratin length for descriptions.

I can work on the styling if you want.

**Comment by LittleSouken** [comment]
Sure, you can
Thank you!

**Comment by Taiwrash** [comment]
@siddhantk232 you are free to make any changes, great work and we move❤️. Thanks @LittleSouken

**Comment by siddhantk232** [comment]
Thanks @LittleSouken and @Taiwrash . I will try to make a PR by tomorrow :)

**Comment by siddhantk232** [comment]
hey @Taiwrash I have fixed the styling issues :)

**Comment by geeks5551** [comment]
can I contribute to this issue? looking interesting

**Comment by LittleSouken** [comment]
Yes, you can. Thank you.
________________________________
De: Shivam Agrahari <notifications@github.com>
Enviado: sábado, 10 de outubro de 2020 10:02
Para: Taiwrash/dev-resume <dev-resume@noreply.github.com>
Cc: NewbieLittleSouken <raymondsouken@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [Taiwrash/dev-resume] Styling issues (#24)


can I contribute to this issue? looking interesting

**Comment by greg7110** [comment]
Hi all!

I see that this issue is not yet resolved.

Can I try to solve it?
